# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef765be4925a13849bff8331242fac154da01a79d8c9516e4908a894f0d0dede2cb0691ca43716e7b7075e7b43d752a731ec90c0a431b2285315c1f6cb122f7d

test:
  secret_key_base: 4e35dc5111b86a6b1601f0b28d452d9a6f8534383c64777c685946b52ed13d753991ba0e3a87f8ba199216edee860dcfcae14b7dc4832c98afaed39d4959cb31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
